# -*- coding: utf-8 -*-
"""sairam_82_26.08.2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OXisPY5UUT2LPNJqerrkF4q9U1tWj72T
"""

# Program to print distinct vowels of the string using set
s = input("Enter a string: ")
s = s.upper()
vowels = {'A', 'E', 'I', 'O', 'U'}
found_vowels = {ch for ch in s if ch in vowels}
result = ""
for ch in s:
    if ch in found_vowels and ch not in result:
        result += ch
print(result)