# -*- coding: utf-8 -*-
"""sairam_82_10.09.2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c6bK64eLw4am8-9LEbz558qkZJMo553o
"""

#1  Towers  of  Hanoi
def  toh(n , p1 , p2 , p3):
	if n > 0:                                              #if  at  least  one  disk:
		toh(n-1, p1, p3, p2)                                 #How  to  move  (n - 1)  disks  from   pole1  to  pole2  and  pole3  is  intermediate  (Use  recursion)
		print(f"{p1} ---> {p3}")                             #How  to  move  disk  from  pole1  to  pole3
		toh(n-1, p2, p1, p3)                                 #How  to  move  (n - 1)  disks  from   pole2  to  pole3  and  pole1  is  intermediate  (Use  recursion)
n = int(input('How many disks ? :   '))
toh(n, 1, 2, 3)                                          #How  to  move  'n'  disks  from   pole1  to  pole3  and  pole2  is  intermediate

#3  Find  outputs  (Home  work)
def  outer():
	x = 10
	def  inner():
		nonlocal  x
		print(x) #15
		x = 20
		print(x) #20
		x += 5  #25
	# End  of  inner  function
	print(x)  #10
	x += 5  #15
	inner()
	print(x) #25
# End  of  outer  function
outer()
print(x) #Error

#3  Find  outputs  (Home  work)
def  outer():
	x = 10
	def  inner():
		print(x) #15
		nonlocal  x
		x = 20
		print(x) #20
		x += 5 #25
	# End  of  inner  function
	print(x)#10
	x += 5  #15
	inner()
	print(x) #15
# End  of  outer  function
outer()

#4  Find   outputs(Home  work)
def  outer():
	x = 10
	def  inner():
		global   x
		x = 20
		print(x) #20
		x += 5 #25
	# End  of  inner  function
	print(x) #10
	x += 5 #15
	inner()
	print(x) #15
# End  of  outer  function
outer()
print(x) #15

#5 Find  outputs(Home  work)
def  outer():
	def  inner():
		nonlocal  x #Error
		x = 20
		print(x) #20
	# End  of  inner  function
	inner()
	print(x) #Error
# End  of  the  function
outer()
print(x) #X is not defined

#6 Find  outputs(Home  work)
def  outer():
	def  inner():
		global   x
		x = 20
		print(x) #20
		x = x + 5 #25
	# End  of  inner  function
	inner()
	print(x) #25
# End  of  the  function
outer()
print(x) #25

#7   Identify  Error
def   f1():
        nonlocal x #nonlocal keyword is not used in outer function

#8 Find  outputs (Home  work)
def  outer():
	a = 10
	b = 20
	def   inner():
		nonlocal   a
		a = 100
		b = 200
		print(a , b)
	# End  of  inner  function
	print(a , b) #10 20
	inner()
	print(a , b) #100 20
#end of outer function
outer()

#9 Find  outputs (Home  work)
def   f1():
	x = 'John'
	def  f2():
		nonlocal  x
		x =  'Hello'
	#end of inner function
	f2()
	return  x
#  End  of  f1()  function
print(f1()) #Hello

#10 Find  output(Home  work)
def  fun():
	x = 10
	def    gun():
		x =  x +  20
		print(x) #Error
	#end of inner function
	gun()
#end of outer function
fun()

#11  Identify  Error
x = 10
def   outer():
	x = 20
	def  inner():
		global   x #Error
		nonlocal  x #cannot use both keywords to same variable

#12  Find  outputs  (Home   work)
def   f1():
	x = 10
	def  f2():
		nonlocal   x
		def  f3():
			nonlocal   x
			print(x)  #10
		f3()
	f2()
f1()