# -*- coding: utf-8 -*-
"""sairam_82_19.08.2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11HVGsm_ErQxJt_Rm4M3cwOGdhWTrKMdw
"""

#1 Modify  the  following  program  with  walrus  operator
a = [10, 20, 15, 12, 14, 15, 18, 19, 15, 12, 25]

try:
    i = -1
    while (i := a.index(15, i + 1)) >= 0:
        print(i)
except ValueError:
    print(f'15 is found {a.count(15)} times')

#2 program  to  determine  first  list  is  a  sublist  of  2nd  list  or  not.
def is_sublist(first, second):
    pos = -1
    try:
        for x in first:
            pos = second.index(x, pos + 1)
        return True
    except ValueError:
        return False

first = list(map(int, input("Enter first list elements separated by space: ").split()))
second = list(map(int, input("Enter second list elements separated by space: ").split()))

print(is_sublist(first, second))

#3 copy()  method  demo program  (Home  work)
a = [10, 20, 15, 18]
b = a.copy()
print(b)           # [10, 20, 15, 18]
print(a is b)      # False
print(a == b)      # True
c = a[:]
print(c)           # [10, 20, 15, 18]
print(a is c)      # False
print(a == c)      # True
d = a
print(d)           # [10, 20, 15, 18]
print(a is d)      # True
print(a == d)      # True

#4 program  to  determine  mode
lst = eval(input("Enter the list: "))
unique_elements = set(lst)
mode = None
max_count = 0
for element in unique_elements:
    count = lst.count(element)
    if count > max_count:
        max_count = count
        mode = element
print("mode =", mode)
print("ctr =", max_count)

#5 Nested  List  demo  program  (Home  work)
a = [[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]]
print(a)      #[[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]]
print(len(a)) #3
print(a[0]) #[10, 20, 30, 40]
print(a[1]) #[50, 60, 70, 80]
print(a[2]) #[90, 100, 110, 120]
print(a[0][2]) #30
print(a[1][3]) #80
print(a[2][1]) #100

#6 Find  outputs  (Home  work)
a = [[10, 20], [30, 40, 50], [60, 70, 80, 90]]
print(a[0]) #[10, 20]
print(a[1]) #[30, 40, 50]
print(a[2]) #[60, 70, 80, 90]
print(len(a[0])) #2
print(len(a[1])) #3
print(len(a[2])) #4

#7 How  to  print  nested  list  in  differnent  ways
a = [[10, 20], [30, 40, 50], [60, 70, 80, 90]]
print('Nested list with print function')
print(a)
print('Each inner list of outer list without indexes')
for inner_list in a:
    print(inner_list)
print('Elements in the form of matrix without using indexes')
for inner_list in a:
    for element in inner_list:
        print(element, end=' ')
    print()
print('Elements in the form of matrix using indexes')
for i in range(len(a)):
    for j in range(len(a[i])):
        print(a[i][j], end=' ')
    print()

#8  Find  outputs (Home  work)
a = [[10 , 20] , [30 , 40] , [50 , 60] , [70 , 80]]
for  x  in  a:
    print(x) #[10, 20]
              [30, 40]
              [50, 60]
              [70, 80]
print()
for  x , y  in  a:
	print(x , y,sep='...') #10...20
                          30...40
                          50...60
                          70...80

#9 Find  outputs (Home  work)
a = [[10 , 20 , 30] , [40 , 50 , 60] , [70 , 80 , 90]]
for  x  in  a:
    print(x)    #[10, 20, 30]
                [40, 50, 60]
                [70, 80, 90]
print()
for  x , y ,  z  in   a:
	print(x , y , z,sep='...')  #10...20...30
                               40...50...60
                               70...80...90

#10 Find  outputs (Home  work)
a = [[10 , 20] , [30 , 40 , 50] , [60 , 70 , 80 , 90]]
for  x  in  a:
	print(x)      #[10, 20]
                 [30, 40, 50]
                 [60, 70, 80, 90]
for  x , y  in  a:
print(x , y,	sep='...') #Error

#11 Find  outputs  (Home  work)
a = [[]]
print(a[0]) #[]
print(a[-1]) #[]

#12  Find  outputs  (Home  work)
a = [[10 , 'Rama' , 1000.0] , [20 , 'Sita' , 2000.0] , [15 , 'Rajesh' , 3500.0] , [18 , 'Kiran' , 2800.0] , [5 , 'Amar'  ,5000.0] ]
print(sorted(a))                         #[[5, 'Amar', 5000.0], [10, 'Rama', 1000.0], [15, 'Rajesh', 3500.0], [18, 'Kiran', 2800.0], [20, 'Sita', 2000.0]]
print(sorted(a , reverse =True))         #[[20, 'Sita', 2000.0], [18, 'Kiran', 2800.0], [15, 'Rajesh', 3500.0], [10, 'Rama', 1000.0], [5, 'Amar', 5000.0]]
print(a)                                 #[[10, 'Rama', 1000.0], [20, 'Sita', 2000.0], [15, 'Rajesh', 3500.0], [18, 'Kiran', 2800.0], [5, 'Amar', 5000.0]]