# -*- coding: utf-8 -*-
"""sairam_82_18.08.2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a2GPlIhcuq0xmgTcU6XwWcje3Gb_xXAY
"""

#1  len()  function demo   program  (Home  work)
a = [ 25, 10.8, 'Hyd', True]
print(len(a)) #4
b = []
print(len(b)) #0
c = [[10 , 20] , 30 , 40]
print(len(c)) #3

#2 sum()  function  demo  program  (Home  work)
a = [25 , 10.8 , True]
print(sum(a))        #36.8
b= [3 + 4j , 5 + 6j]
print(sum(b))        #8+10k
c = [25 , 10.8 , True , 3 + 4j , False]
print(sum(c))        #39.8+4j
d = [10 , 20 , 15 , 18]
print(sum(d))        #63
e = [25 , 10.8 , 'Hyd' , True]
#print(sum(e)) #Error

#3 Find  outputs
a = [[10, 20, 15, 18]]
print(sum(a))        # [10, 20, 15, 18]
print(sum(a[0]))     # 63
print(sum([x for x in a]))  #63

#4 max()  and  min()  functions  demo  program  (Home  work)
a = [10 , 20 , 15 , 18 , 30, 5 , 12]
print(max(a)) #30
print(min(a)) #5
b = ['Rama' , 'Sita' , 'Rajesh' , 'Kiran' , 'Amar' , 'Vamsi' , 'Manohar']
print(max(b)) #Vamsi
print(min(b)) #Amar
c = [25 , 10.8 ,  3 + 4j , True]
print(max(c)) #Error
d = [25 , '35']
print(max(d))  #Error
print(max([])) #Error
print(min([])) #Error

#5 list()  function  demo  program
a = (10 , 20 , 15, 18)
b = list(a)
print(b)  #[10, 20, 15, 18]
print(type(b)) #<class 'list'>
print(a  is  b) #False
print(a==b) #False

#6  Find  outputs (Home  work)
a = range(4 , 10 , 2)
b = list(a)
print(b) #[4, 6, 8]
print(type(b)) #<class 'list'>
a = list('Vamsi') #['V', 'a', 'm', 's', 'i']
print(a)  #['V', 'a', 'm', 's', 'i']
a = list()
print(a)#[]
print(list(25)) #Error
print(list(10.8)) #Error
print(list(True)) #Error
print(list(None)) #Error

#7 Find  outputs (Home  work)
a = ((10 , 20) , (30 , 40 , 50) , (60 , 70 , 80 , 90))
print(list(a))                                              #[(10, 20), (30, 40, 50), (60, 70, 80, 90)]
b = { (10 , 20) , (30 , 40 , 50) , (60 , 70 , 80 , 90)}
print(list(b))                                              #[(30, 40, 50), (60, 70, 80, 90), (10, 20)]
c = ([10 , 20] , (30 , 40) , {50 , 60})
print(list(c))                                              #[[10, 20], (30, 40), {50, 60}]

#8 sorted()  function   demo  program
a = [10 , 20 , 15 , 5 , 12]
b = sorted(a)
print(b)                                #[5, 10, 12, 15, 20]
print(type(b))                          #<class 'list'>
c = sorted(a , reverse = True)
print(c)                               #[20, 15, 12, 10, 5]
print(a)                               #[10, 20, 15, 5, 12]

#9 Find  outputs  (Home  work)
a = ['Rama',  'Rajesh',  'Amar',  'Sita',  'Vamsi'  ,  'Kiran'  , 'Rama  Rao']
b = sorted(a)
print(b)                                #['Amar', 'Kiran', 'Rajesh', 'Rama', 'Rama  Rao', 'Sita', 'Vamsi']
c = sorted(a , reverse = True)
print(c)                                #['Vamsi', 'Sita', 'Rama  Rao', 'Rama', 'Rajesh', 'Kiran', 'Amar']
print(a)                                #['Rama', 'Rajesh', 'Amar', 'Sita', 'Vamsi', 'Kiran', 'Rama  Rao']

#10 all()  function demo  program  (Home  work)
a = [12 > 10 , 5 < 20 , 30 == 30]
print(all(a)) #True
b = [9 >= 6 , 12 <= 9 , 6 == 6]
print(all(b)) #False
c = [25 , 10.8 , '' , True , 3+4j , 'Hyd']
print(all(c)) #False
d = [10 , 0 , 20]
print(all(d)) #False
e = []
print(all(e)) #True

#11 any()  function demo program  (Home  work)
a  = [12 > 18 , 5 < 20 , 35 == 30]
print(any(a)) #True
b = [12 > 18 , 25 < 20 , 35 == 30]
print(any(b)) #False
c = [0 , 0.0 , '' , 25 , 0 + 0j , False]
print(any(c)) #True
d = [0 , 0.0 , '' , 0 + 0j , False]
print(any(d)) #False
e = []
print(any(e)) #False

#12 del  operator  demo  program (Home  work)
a = [10 , 20 , 15 , 18]
print(a) #[10, 20, 15, 18]
del    a[2]
print(a) #[10, 20, 18]
del  a[3] #Error
del  a #Error
print(a) #[10, 20, 18]

#13  append()  method  demo  program (Home  work)
list = [10 , 20 , 15 , 18]
print(list)  #[10, 20, 15, 18]
list . append(19)
print(list)  #[10, 20, 15, 18, 19]

#14  Find  outputs (Home  work)
list = []
print(list)  #[]
list . append(25)
list . append(10.8)
list . append('Hyd')
list . append(True)
print(list)   #[25, 10.8, 'Hyd', True]

#15 Find  outputs  (Home  work)
list = []
for  x  in   range(0 , 50 , 10):
	list . append(x)
print(list) #[0, 10, 20, 30, 40]

#16 Find  outputs  (Home  work)
a = [10, 20, 30]
a.append('Hyd')
print(a)            # [10, 20, 30, 'Hyd']
print(len(a))       # 4
print(a[3])         # Print 4th element of list 'a', Output: Hyd
print(a[3])         # Print 'H'
print(a[10][11])    # Error
print(a[10][12])    # Error

#17 remove()  method  demo  program  (Home  work)
try:
	list = [10 , 20 , 15 , 18 , 15 , 12 , 15 , 19]
	list . remove(15)
	print(list) #[10, 20, 18, 15, 12, 15, 19]
	list . remove(25)
except:
	print('25  is   not  in  the  list') #25  is   not  in  the  list

#18 program  to  delete  'all'  occurences  of  'x'  from  the  list
lst = input("Enter List : ")
lst = lst.strip('[]').split(',')
lst = [int(x.strip()) for x in lst]
x = int(input("Enter element to be deleted : "))
result = [item for item in lst if item != x]
print(f"List without {x}'s : {result}")

#19 clear() method  demo program  (Home  work)
list = [10 , 20 , 15 , 18]
print(list) #[10, 20, 15, 18]
list . clear()
print(list) #[]

#20 reverse()  method  demo  program (Home  work)
a = [10 , 20 , 15 , 18]
print(a) #[10, 20, 15, 18]
a . reverse()
print(a) #[18, 15, 20, 10]

#21  sort()  method  demo  program (Home  work)
list = [10 , 20 , 15 , 18 , 5]
print(list) #[10, 20, 15, 18, 5]
list . sort()
print(list) #[5, 10, 15, 18, 20]
list . sort(reverse = True)
print(list) #[20, 18, 15, 10, 5]

#22 Find  outputs (Home  work)
a = ['Rama' , 'Rajesh' , 'Amar' ,  'Sita' ,  'Vamsi' , 'Kiran' , 'Rama  Rao']
print(a) #['Rama', 'Rajesh', 'Amar', 'Sita', 'Vamsi', 'Kiran', 'Rama  Rao']
a . sort()
print(a) #['Amar', 'Kiran', 'Rajesh', 'Rama', 'Rama  Rao', 'Sita', 'Vamsi']
a . sort(reverse=True)
print(a) #['Vamsi', 'Sita', 'Rama  Rao', 'Rama', 'Rajesh', 'Kiran', 'Amar']

#23 Identify  error (Home  work)
a = [25 , 10.8 ,  'Hyd' ,  True]
a.sort()    #Typeerror

#24  count()  method  demo    program (Home  work)
a = [10 , 20 , 15 , 18 , 15 , 12 , 14 , 15 , 19]
print(a . count(15)) #3
print(a . count(25)) #0
print(len(a))#9

#25 Tricky  program
#program  to  remove  all  duplicate  elements  of  the  list  (Not  even  single  occurance)
lst = input("Enter list elements separated by space: ").split()
lst = [int(x) for x in lst]

result = []
for item in lst:
    if lst.count(item) == 1:
        result.append(item)

print(result)

#26 program  to  determine  all  the  list  elements  are  identical  or  not
lst = [int(x.strip()) for x in input("Enter list elements").split(',')]

if lst.count(lst[0]) == len(lst):
    print("All the elements are identical")
else:
    print("All the elements are not identical")

print(len(lst))
print(lst.count(lst[0]))

#27 index()  method  demo  program  (Home  work)
# index() method demo program (Home work)
a = [10, 20, 15, 12, 14, 15, 18, 19, 15, 12, 25]
#     0   1   2   3   4   5   6   7   8   9   10
try:
    i = a.index(15)
    while True:
        print(i)                    # 2
        i = a.index(15, i + 1)
        print(i)                    # 5
        i = a.index(15, i + 1)
        print(i)                    # 8
        i = a.index(15, i + 1)      # Error
except:
    print(f'15 is found {a.count(15)} times')  # 15 is found 3 times