# -*- coding: utf-8 -*-
"""sairam_82_22.08.2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UbCa8gHXJCXWtxjwDCAGsWrNqIBDlj1t
"""

#1 index()  and  count()  methods  demo  program   (Home  work)
a = (10 , 20 , 15 , 12 , 14 , 15 , 18 , 19 , 15 , 12 , 25)
#     0    1      2     3    4     5     6    7     8    9    10
try:
	i = a . index(15)
	while  True:
		print('15 is found at index : ' , i)
		i = a . index(15 , i + 1)
except:
		print(F'15  is  found  {a . count(15)}  times')

#2  How  to  modify  an  element  of  tuple ?    (Home  work)
a = (10, 20, 30, 40, 50)
print(a) #(10, 20, 30, 40, 50)
print(id(a)) #Prints Address of object A
a = a[:2] + (35,) + a[3:]
print(a) #(10, 20, 35, 40, 50)
print(id(a)) #prints Address of object a

#3 How  to  delete  an  element  of  tuple ?   (Home  work)
a  = 10,20,30,40,50
a . remove(30) #Error
del  a[2]#Error
a . pop(2) #Error
print(a) #(10, 20, 30, 40, 50)
print(id(a)) #prints Address of object a
a = a[:2] + a[3:]
print(a)  #(10, 20, 40, 50)
print(id(a)) #prints Address of object a

#4  Nested   tuple  (Home  work)
a = ( (10 , 20)  ,  (30 , 40 , 50)  ,  (60 , 70 , 80 , 90) )
print(a)                    #((10, 20), (30, 40, 50), (60, 70, 80, 90))
print(type(a))              #<class 'tuple'>
print(len(a))               #3
print(a[0])                 # (10, 20)
print(a[1])                 # (30, 40, 50)
print(a[2])                 # (60, 70, 80, 90)
print(a[0])                 # (10, 20)2
print(a[1])                 # (30, 40, 50)
print(a[2])                 #(60, 70, 80, 90)

#5 Find  outputs  (Home  work)
a = ((10, 20, 30),)
print(a[0]) #(10, 20, 30)
(inner_tuple,) = a
print(inner_tuple) #(10, 20, 30)
print(a[0])    # (10, 20, 30)
print(a)    # ((10, 20, 30),)
print(a)    # ((10, 20, 30),)
b = ((),)
print(b)     #((),)
(inner_empty_tuple,) = b
print(inner_empty_tuple) #()

#6 Find  outputs (Home  work)
a = ((10 , 20 , 30))
print(a)  #(10, 20, 30)
print(*a) #10 20 30
b = (())
print(b) #()
print(*b)

#7 What  are  the  outputs  if  input  is  {10 , 20 , 15 , 18 , 20 , 12 , 18}
a = input('Enter  Set  :  ') # {10 , 20 , 15 , 18 , 20 , 12 , 18}
print(a)                     # {10 , 20 , 15 , 18 , 20 , 12 , 18}
print(type(a))               #<class 'str'>
b = eval(a)
print(b)                    #{18, 20, 10, 12, 15}
print(type(b))              #<class 'set'>

#8  Find  outputs  (Home  work)
print({(10 , 20 , 30)}) #{(10, 20, 30)}
print({[10 , 20 , 30]}) #Error
print({{10 , 20 , 30}}) #Error
print({{}}) #Error

#9 How  to  print  set  in  differnet ways  (Home  work)
a = {25, True, 'Hyd', 10.8}
print('Set with print function:') #Set with print function:
print(a)                          #{25, 10.8, 'Hyd', True}
print('Iterate elements of set with for loop:')  #Iterate elements of set with for loop:
for element in a:
    print(element) #25
                   #10.8
                  #Hyd
                  #True

#10 Find  outputs  (Home  work)
a = 'Hyd'
b = True
c = 25
d = 1
e = 'Hyd'
s = {a , b , c , d , e}
print(s) #{True, 'Hyd', 25}
print(len(s)) #3
print(type(s)) #<class 'set'>

#11 Find  outputs  (Home  work)
s = {'Hyd',  25,  True,  10.8 }
print(s) #{25, 10.8, 'Hyd', True}
a , b , c , d = s
print(a) #25
print(b) #10.8
print(c) #Hyd
print(d) #True

#12 Find  outputs  (Home  work)
s = {'Hyd',  25,  True,  10.8 }
print(s)         #{25, 10.8, 'Hyd', True}
a , *b = s
print(a)        #25
print(b)       #[10.8, 'Hyd', True]
print(type(b)) #<class 'list'>

#13 Find  outputs  (Home  work)
s = {'Hyd',  25,  True,  10.8 }
print(s) #{25, 10.8, 'Hyd', True}
a , *b , c = s
print(a) #25
print(b) #[10.8, 'Hyd']
print(c) #[10.8, 'Hyd']

#14 Find  outputs  (Home  work)
s = {20 , 10 , 20 , 10}
print(s) #{10, 20}
x , y = s
print(x) #10
print(y) #20

#15 set()  function  demo  program  (Home  work)
a = range(100 , 151 , 10)
b = set(a)
print(b) #{130, 100, 140, 110, 150, 120}
c = [10 , 20 , 15 , 18 , 10 , 50 , 20 , 12 , 18]
d = set(c)
print(d) #{10, 12, 15, 18, 50, 20}
e = set('Rama  rAo')
print(e) #{'R', 'a', 'o', 'r', 'm', ' ', 'A'}
print(set(25)) #Error
print(set()) #set()