# -*- coding: utf-8 -*-
"""sairam_82_03.09.2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xGAtPQcZ1Z77nHYlNqu3qc-eJ_X4CFQG
"""

#1 Find  outputs  (Home  work)
def   f1():
  a = 20
  print(a)           # 10
  dict = globals()
  print(dict['a'])   # 20
  a = 30
  dict['a'] = 40
#  End  of  f1()  function
a = 10
print(a)             # 10
#a +=1
f1()
print(a)             # 40

#2Find  outputs (Home  work)
x = 10
def   f1():
	print(x) #10
	print(globals()['x']) #10
# End of the function
f1()

#3 Find  outputs (Home  work)
def  f1():
	x = 20
	print(x) #20
	print(globals()['x']) #Error
# End  of  the  function
f1()

#4 Find outputs (Home  work)
def  f1():
	a = 40
	b = 50
	c = 60
	print(a , b , c) #40 50 60
	dict = globals()
	print(dict['a'] , dict['b'] , dict['c'])
	dict['a'] = 100
	dict['b'] = 200
	dict['c'] = 300
def  f2():
	print(a , b , c) #100 200 300
# End  of  f2  function
a = 10
b = 20
c=30
f1()
f2()

#5 global  keyword  demo  program (Home  work)
def    f1():
	x = 20
	print(x) #20
def   f2():
	global  x
	x = 30
	print(x) #30
	x += 1 #31
def   f3():
	global  y
	y = 40
	print(y) #40
	y += 1  #41
def   f4():
	x = 50
	global   x  #Error
#  End  of  the  functions
x = 10
print(x) #10
x += 1 #11
f1() #20
print(x) #11
f2() #30
print(x) #31
x += 1 #32
f3() #40
print(y) #41
f4() #Error
print(x)

#6 Find outputs (Home  work)
def  f1():
	global  a
	a = 20
	print(a)  #20
	print(globals()['a'])  #20
	a = 30 #30
# End of the function
a = 10
print(a)  #10
f1()
print(a)  #30

#7 Find  outputs(Home  work)
def  f1():
	global  a
	print(a)  #Error
	a = 10
	print(globals()['a'])
	a = 20
	print(a)
	a = 30
def  f2():
	print(a)
# End  of   f2   function
f1()  #Error
f2()
print(a)

#8 Find outputs (Home  work)
def  f1():
	global   a
	a = 10
	print(a)  #10
	a = 20   #20
def  f2():
	global  a
	print(a)
	a = 30
def  f3():
	print(a)
	globals()['a'] = 40
# End  of  the  function
f1()
f2()
f3()
print(a)

#9 Find outputs (Home  work)
def  f1():
	global   a
	a = 10
	print(a)   #10
	a = 20  #20
def  f2():
	print(a)   #Error
	a = 30     #Error
	print(a)
def  f3():
	print(a)
	globals()['a'] = 40
# End  of  the  function
f1()
f2()    #Error
f3()
print(a)

#10  Find  outputs (Home  work)
def  f1():
        a = 10
        global  a  #Error
        print(a)
        global  b
        b = 20
# End  of  f1()  function
f1()
print(a)
print(b)

#11 Find outputs (Home  work)
def  f1():
        global  a
        print(a)  #11
        a += 1  #12
def  f2():
        global  a
        print(a)   #13
        a += 1    #14
# End  of  the  function
a = 10
print(a)   #10
a += 1    #21
f1()    #11
print(a) #12
a += 1  #13
f2() #13
print(a) #14

#12 Find  outputs (Home  work)
def   f1():
	a = 20
	print(a) #20
def  f2():
	print(a) #Error
	a += 1 #Error
# End of the function
a = 10
print(a) #10
f1()  #20
a +=1    #11
f2() #Error
print(a)

#13 Find outputs (Home  work)
def  f1():
	a = 20
	global   a   #Error
	print(a)
	print(globals()['a'])
	a = 30
	globals()['a'] = 40
#  End  of  f1()   function
a = 10
print(a)    #10
a +=1       #11
f1()       #Error
print(a)

#14 Find   outputs
def   f1():
	x = x + 5   #Error
# End  of  f1  function
def  f2():
	x = globals()['x'] + 5
	print(x)    #!5
# End of f2  function
x = 10
f1()       #Error
f2()
print(x)