# -*- coding: utf-8 -*-
"""sairam_82_13.08.2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iJRYwaDS6brMVcEwbgZToSb3LzZSmgpP
"""

#1 program  to  print  distinct  vowels  of  the  string  without  using  set
s=input("Enter a string:")
vowels="AEIOU"
found=""
for ch in s.upper():
    if ch in vowels and ch not in found:
        found=found+ch
print(found)