# -*- coding: utf-8 -*-
"""sairam_82_11.09.2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KmJOD55gqRCQnOMCyl_bqAdiYuwwmxno
"""

#1  Find  outputs  (Home  work)
def  f1():
	print('f1  function')
def   f2(fun):
	print('f2  function')
	fun()
	print('Back  to  f2  function')
# end of the function
print('Begin') #BEgin
f2(f1) #f2 function #f1 function #Back to f2 function
print('End') #End

#2  Find  outputs  (Home  work)
def  f1():
	print('f1  function')
def   f2 (fun):
	print('f2  function')
	fun()
	print('Back  to  f2  function')
# end of the function
print('Begin') #Begin
f2(f1()) #f1 function #f2 function #Error
print('End') #End

#3 Find  outputs (Home  work)
def   outer():
	print('Outer  Function')
	def  inner():
		print('Inner function')
	return   inner
# End  of  the  function
fun = outer()
print('Hello') #Hello
fun()
print('Bye') #Bye
inner() #Error

#4 Find  outputs (Home  work)
def  outer(x):
	print('Outer  Function') #Outer function
	def  inner1(): #
		print('1st  inner  function') #1st inner function
	# End  of  inner1
	def  inner2():
		print("2nd  inner  function") # 2nd inner function
	# End  of  inner2
	if   x == 10:
		return  inner1
	else:
		return  inner2
#end of the function
f1 = outer(10)
f2 = outer(20)
f1()
f2()

#4 Find  outputs  (Home  work)
def   outer(msg):
	def  inner():
		print(msg) #Hi Hello
	return  inner
# End  of  the  function
hi_fun = outer('Hi')
hello_fun = outer('Hello')
hi_fun()
hello_fun()

#5 Find  outputs  (Home  work)
def   decor(fun):
	print(fun . _name_) #f1
	def   inner():
		return   fun() +  2
	return  inner
@decor #f1=decor(f1)
def   f1():
	return  10
# End of the function
print('End') #End

#6  How  to  call  f1()  function  when  @decor  tag  is  missing  ?
def   decor(fun):
	def   inner():
		x = fun()
		return   x + 2
	return  inner
def  f1():
        return  10
#end  of  the  function
f1 = decor(f1)
print(f1()) #12

#7 Find  outputs(Home  work)
def   decor(fun):
	print(fun . _name_)#wish
	def    inner(name):
		if   name  == 'Python':
			print('Hello' , name) #Hello Python
		else:
			fun(name)
	return  inner
@decor
def    wish(name):
        print('Hi' , name)#Hi Java
# End  of  the  function
wish('Python')
wish('Java')

#8 Find  outputs(Home  work)
def   decor(fun):
	def  inner(x , y):
		try:
			return  fun(x , y)
		except:
			return   'Division   by  0  is  not  permitted'
	return  inner
@decor
def  div(a , b):
        return  a / b
# End  of  the  function
print(div(10 , 3)) #3.33
print(div(10 , 0)) #Division by 0 is not permitted
print(inner(10 , 3)) #Error

#9 Modify  following  div  function  such  that  div(9 , 2)   and   div(2 , 9)  should  return  4.5  only
def  decor(fun):
def inner(a, b):
        big = max(a, b)
        small = min(a, b)
        return fun(big, small)
    return inner#How  to  decorate  the  function  such  that  4.5  is  returned
@decor
def  div(a , b):
    return   a /b

print(div(9 , 2))
print(div(2,9))

#10  Find  outputs (Home  work)
def   decor(fun):
	def   inner():
		print(F'Decorating  {fun . _name_}  function') #Decorating f1 function
		fun()
		print('Decoration  is  finished') #Decorating is finished
	return  inner
@decor
def   f1():
	print('Hello') #Hello
# End  of  the  function
f1()
print('Bye') #Bye

#  Most  tricky   program
# Same  decorator  to  multiple  functions  with  different  signatures
def   decor(fun):
	print(fun . _name_) # f1, f2, f3, f4
	def   inner(*x):  #   *  is  var-arg  parameter
		print(x)
		fun(*x)  #  *  unpacks  object  'x'
		print('End  of  decoration') # End of decoration
	return  inner
@decor
def   f1(x):
	print('f1  function  :  ' , x) #f1
@decor
def   f2(x , y):
	print('f2  function  :  ' , x , y ) #f2
@decor
def  f3(x , y , z):
	print('f3 function : ' , x , y , z) #f3
@decor
def   f4():
	print('f4 function') #f4
# end of function
f1(10) # (10,) # f1 function : 10 # End of decoration
f2(25 , 10.8) # (25, 10.8) # f2 function : 25 10.8 # End of decoration
f3('Hyd' ,  True,3+4j) # ('Hyd', True, (3+4j)) # f3 function : Hyd True (3+4j) # End of decoration
f4() # () # f4 function # End of decoration