# -*- coding: utf-8 -*-
"""sssdp 30-07-2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/174Ryq3dsUN6idYyCmpi_1ie27zQVO-DL
"""

# A program  to  print  full  pyramid
n = int(input("Enter the number of lines: "))

for i in range(1, n + 1):
    print(" " * (n - i), end="")
    print("*" * (2 * i - 1))