# -*- coding: utf-8 -*-
"""sairam_82_13.08.2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wWk_D6m2ibJ4l9bQY2H3gUyx1hFfChLa
"""

#program  to  print  distinct  vowels  of  the  string  without  using  set
s = input("Enter a string: ")
s = s.upper()
vowels = "AEIOU"
result = ""

for ch in s:
    if ch in vowels and ch not in result:
        result += ch

print(result)