#*********************** -*- coding: utf-8 -*-
"""introduction_codes .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Okjaftk764cO-cmjP_61fzYR2QJTCsu3
"""

#***********************Postive or negative number
n=int(input("enter num: "))
if n>0:
    print("positive")
elif n<0:
    print("negative")
else:
    print('zero')

#***********************even or odd
n=int(input("enter num: "))
if n%2==0:
  print('even')
else:
  print("odd")

#***********************sum of n natural num
n=int(input("enter num: "))
a=0
for i in range(n+1):
  a+=i
print(a)

5#***********************sum in given range
n=int(input("enter from num: "))
m=int(input("enter to num: "))
a=0
for i in range(n,m+1):
  a+=i
print(a)

#***********************greatest of 2 num
n=int(input("enter 1st num: "))
m=int(input("enter 2nd num: "))
print(max(n,m))

#***********************greatest of 3 num
n=int(input("enter 1st num: "))
m=int(input("enter 2nd num: "))
p=int(input("enter 3rd num: "))
print(max(n,m,p))

#***********************leap year
n=int(input("enter 1st num: "))
if (n%400==0) or (n%4==0 and n%100!=0):
  print("leap year")
else:
  print("not leap year")

#***********************prime num
n=int(input("enter 1st num: "))
for i in range(2,n):
  is_prime=True
  if n%i==0:
    is_primt=False
  break
if is_prime:
  print('prime')
else:
  print('not prime')

#*********************** prime num
n=int(input("enter 1st num: "))
a=[]
for i in range(2,n+1):
  is_prime=True
  for j in range(2,i):
    if i%j==0:
      is_prime=False
      break
  if is_prime:
    a.append(i)
print(a)

#*********************** range of prime num
n=int(input("enter 1st num: "))
m=int(input("enter 2st num: "))
a=[]
for i in range(n,m+1):
  is_prime=True
  for j in range(2,i):
    if i%j==0:
      is_prime=False
      break
  if is_prime:
    a.append(i)
print(a)

#***********************sum of digits
n=(input("enter 1st num: "))
a=0
for i in n:
  a+=int(i)
print(a)

#***********************rev a num
n=int(input("enter 1st num: "))
a=0
while n>0:
  rem=n%10
  a=a*10+rem
  n=n//10
print(a)

#***********************palindrome
n=(input("enter 1st num: "))
is_palin=True
for i in range(len(n)//2):
  if n[i]!=n[-(i+1)]:
    is_palin=False
    break
if is_palin:
  print('palindrome')
else:
  print('not palindrome')

#***********************armstrong
n=(input("enter 1st num: "))
a=0
for i in n:
  a+=int(i)**len(n)
if int(n)==a:
  print('armstrong')
else:
  print('not armstrong')

#***********************range armstrong
n=int(input("enter 1st num: "))
m=int(input("enter 2 num: "))
b=[]

for i in range(n,m+1):
  a=0
  s=str(i)
  for j in s:
    a+=int(j)**len(s)
  if a==i:
    b.append(a)
print(b)

#***********************fibb upto n th term
def fibb(n):
  if n==0:
    return 0
  elif n==1:
    return 1
  else:
    return fibb(n-1)+fibb(n-2)
n=int(input("enter 1st num: "))
for i in range(n):
  print(fibb(i),end=' ')

#***********************fibb  n th term
def fibb(n):
  if n==1:
    return 0
  elif n==2:
    return 1
  else:
    return fibb(n-1)+fibb(n-2)
n=int(input("enter 1st num: "))
print(fibb(n))

#***********************factorial
def fact(n):
  if n==1 or n==0:
    return 1
  elif n<0:
    return 'num must be positive'
  else:
    return n*fact(n-1)
n=int(input("enter 1st num: "))
print(fact(n))

n=int(input("enter 1st num: "))
m=int(input("enter 2 num: "))
print(n**m)

#***********************factor of num
n=int(input("enter 1st num: "))
a=[]
for i in range(2,n):
  if n%i==0:
    a.append(i)
print(a)

#***********************strong num
def strong_num(n):
  if n==0 or n==1:
    return 1
  else:
    return n*strong_num(n-1)
n=(input("enter 1st num: "))
a=0
for i in n:
  a=a+(strong_num(int(i)))
if a==int(n):
  print('strong num')
else:
  print('not strong num')

#***********************perfect num
n=int(input("enter 1st num: "))
a=0
for i in range(1,(n//2)+1):
  if n%i==0:
    a+=i
if a==n:
  print('perfect num')
else:
  print('not perfect num')

#***********************automarphic num
n=int(input("enter 1st num: "))
a=str(n)
b=str(n**2)
if b.endswith(a):
  print('automarphic num')
else:
  print('not automarphic num')

#***********************harshad num
n=(input("enter 1st num: "))
a=0
for x in n:
  a+=int(x)
if int(n)%a==0:
  print('harshad num')
else:
  print('not a harshad num')

from re import I
#***********************abudent num
n=int(input("enter 1st num: "))
a=0
for i in range(1,n):
  if n%i==0:
    a+=i
if a>n:
  print('abudent num')
else:
  print('not abudent num')

#***********************friendly pair
n = list(map(int, input("Enter two numbers: ").split()))
b=[]
for i in range(len(n)):
  a=0
  for j in range(1,(n[i]//2)+1):
    if n[i]%j==0:
      a+=j
  b.append(a)
for i in range(len(b)-1):
  if n[i]/b[i]==n[i+1]/b[i+1]:
    print('friendly pair ')
  else:
    print('not friendly pair')